version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - mobiletta
  assignees:
  - mobiletta
  labels:
  - dependabot
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.9.0
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.146.0
    - 0.147.0
    - 0.148.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: firebase-ci
    versions:
    - 0.15.0
  - dependency-name: node-notifier
    versions:
    - 9.0.0
  - dependency-name: yup
    versions:
    - 0.32.8
  - dependency-name: redux-firestore
    versions:
    - 0.14.0
